name: AngularDartSurveyCCH3
description: Angular Dart Survey Examples CH3 application
dependencies:
  angular: 0.10.0
  bloodless: any
  browser: any
  http: any
  quiver: any
  shadow_dom: any
dev_dependencies:
  unittest: any
transformers:
- angular
