name: AngularDartSurveyCh1
description: A sample web application
dependencies:
  angular: 0.10.0
  bloodless: any
  browser: any
  shadow_dom: any
transformers:
- angular
- $dart2js:
    minify: true
